include: package:very_good_analysis/analysis_options.4.0.0.yaml
analyzer:
  exclude:
    - build/**
    - "**/*.g.dart"
linter:
  rules:
    file_names: false
    lines_longer_than_80_chars: false
    public_member_api_docs: false
    sort_constructors_first: false
    unnecessary_library_directive: false
