name: auth_storage
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  json_annotation: ^4.8.0
  orm: ^3.3.0

dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  lints: ^2.0.1
  test: ^1.24.2
