name: frog_auth_demo
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  auth_storage:
    path: ../server/packages/auth_storage/

  dart_frog: ^0.3.6
  dartz: ^0.10.1

  models:
    path: ../server/packages/models/

  orm: ^3.3.0

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.24.2
  very_good_analysis: ^4.0.0
